#!/usr/bin/env python3
"""Generate LaTeX tables of VQ-code GO enrichment and VQ-WGCNA overlap for the
post-fix v2.0 runs (10k + 25k), for inclusion in manuscript.tex.

Emits:
  1. VQ-code GO enrichment tables (one per run x comparison) — every enriched
     GO term (p<0.05) for every FDR-significant VQ code.
  2. VQ-WGCNA overlap tables (one per run x comparison) — every FDR-significant
     (q<0.05) code x module pair, with fold-enrichment and the module's own top
     eigengene-enriched term.

Usage:
    python scripts/generate_ms_tables.py [--out output/ms_tables.tex]
"""
import argparse
import csv
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
csv.field_size_limit(sys.maxsize)


def load_rows(path):
    with open(path) as f:
        return list(csv.DictReader(f))


def esc(s):
    """LaTeX-escape a plain string."""
    s = str(s)
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'),
                 ('#', r'\#'), ('_', r'\_'), ('^', r'\^{}'),
                 ('$', r'\$'), ('{', r'\{'), ('}', r'\}')]:
        s = s.replace(a, b)
    return s


def fmt_p(p):
    p = float(p)
    return f"${p:.1e}$" if p < 1e-3 else f"${p:.3f}$"


def module_go_map(wgcna_dir, comparison, group_names):
    """Map 'group/module_color' -> top eigengene GO term for the module."""
    out = {}
    for group in group_names:
        for csvp in glob.glob(
                os.path.join(wgcna_dir, comparison, 'eigengene_enrichments',
                             group, 'eigengene_enrichments.csv')):
            rows = load_rows(csvp)
            by_mod = {}
            for r in rows:
                mod = r['module_color']
                p = float(r['p_value'])
                if mod not in by_mod or p < by_mod[mod][0]:
                    by_mod[mod] = (p, r['term_name'])
            for mod, (p, term) in by_mod.items():
                out[f"{group}/{mod}"] = (p, term)
    return out


def go_table(rows, genes, sigcodes, label, caption):
    """Emit a longtable of GO terms for significant codes."""
    L = []
    L.append(r"\begin{longtable}{r r c l l c}")
    L.append(r"\caption{" + caption + r"}\label{" + label + r"}\\")
    L.append(r"\toprule")
    L.append(r"Code & \#genes & $q$ & Source & GO term & $p$ \\")
    L.append(r"\midrule")
    L.append(r"\endfirsthead")
    L.append(r"\toprule Code & \#genes & $q$ & Source & GO term & $p$ \\"
             r"\midrule \endhead")
    rows_by_code = {}
    for r in rows:
        rows_by_code.setdefault(r['vq_code'], []).append(r)
    for code in sorted(sigcodes, key=lambda c: float(genes[c]['q_value'])):
        if code not in rows_by_code:
            continue
        g = genes[code]
        ng = len(g['gene_names'].split(';'))
        q = float(g['q_value'])
        for tr in sorted(rows_by_code[code], key=lambda r: float(r['p_value'])):
            L.append(f"{code} & {ng} & ${q:.2e}$ & {esc(tr['source'])} & "
                     f"{esc(tr['term_name'])} & {fmt_p(tr['p_value'])} \\\\")
    L.append(r"\bottomrule")
    L.append(r"\end{longtable}")
    return "\n".join(L)


def overlap_table(rows, mmap, universe, label, caption):
    """Emit a longtable of FDR-significant VQ-WGCNA overlap pairs."""
    sig = [r for r in rows if float(r['fisher_q']) < 0.05]
    sig.sort(key=lambda r: float(r['fisher_q']))
    L = []
    L.append(r"\begin{longtable}{r l c c c c c p{4.6cm}}")
    L.append(r"\caption{" + caption + r"}\label{" + label + r"}\\")
    L.append(r"\toprule")
    L.append(r"Code & Module & $N_{\rm vq}$ & $N_{\rm wgc}$ & $n_{\cap}$ & "
             r"fold & $q$ & Module top term \\")
    L.append(r"\midrule")
    L.append(r"\endfirsthead")
    L.append(r"\toprule Code & Module & $N_{\rm vq}$ & $N_{\rm wgc}$ & "
             r"$n_{\cap}$ & fold & $q$ & Module top term \\"
             r"\midrule \endhead")
    for r in sig:
        nv, nw, no = int(r['n_vq_genes']), int(r['n_wgcna_genes']), int(r['n_overlap'])
        fold = no / max(nv * nw / universe, 1e-9)
        q = float(r['fisher_q'])
        mod = r['wgcna_module']
        mterm = "---"
        if mod in mmap:
            mp, mt = mmap[mod]
            mterm = f"{esc(mt)} (${mp:.0e}$)"
        L.append(f"{r['vq_code']} & {esc(mod)} & {nv} & {nw} & {no} & "
                 f"{fold:.2f} & ${q:.2e}$ & {mterm} \\\\")
    L.append(r"\bottomrule")
    L.append(r"\end{longtable}")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out', default='output/ms_tables.tex')
    args = ap.parse_args()

    OUT = []
    OUT.append(r"% Auto-generated by scripts/generate_ms_tables.py — do not edit by hand.")
    OUT.append("")

    configs = [
        # run, comparison, genes_for_go, vq_code_enrichment csv, wgcna_dir
        ('10k_v2.0', 'infection',
         'output/10k_v2.0/figures/infection_genes_for_go.csv',
         'output/10k_v2.0/wgcna/infection/vq_wgcna_term_comparison/vq_code_enrichment_sequential.csv',
         'output/10k_v2.0/wgcna'),
        ('10k_v2.0', 'sex',
         'output/10k_v2.0/figures/sex_genes_for_go.csv',
         'output/10k_v2.0/wgcna/sex/vq_wgcna_term_comparison/vq_code_enrichment_sequential.csv',
         'output/10k_v2.0/wgcna'),
        ('25k_v2.0', 'sex',
         'output/25k_v2.0/figures/sex_genes_for_go.csv',
         'output/25k_v2.0/wgcna/sex/vq_wgcna_term_comparison/vq_code_enrichment_sequential.csv',
         'output/25k_v2.0/wgcna'),
    ]

    run_label = {'10k_v2.0': '10k', '25k_v2.0': '25k'}
    for run, comp, gf_path, go_path, wgcna_dir in configs:
        genes = {r['vq_code']: r for r in load_rows(gf_path)}
        sig = {c for c, r in genes.items() if float(r['q_value']) < 0.05}
        go_rows = load_rows(go_path)
        OUT.append(go_table(
            go_rows, genes, sig,
            f"tab:vq-go-{run_label[run]}-{comp}",
            f"Enriched GO terms of FDR-significant VQ codes, {run_label[run]} "
            f"gene set, {comp} comparison."))
        OUT.append("")

    overlap_configs = [
        ('10k_v2.0', 'infection',
         'output/10k_v2.0/wgcna/infection/vq_wgcna_comparison/vq_wgcna_overlap_infection_sequential.csv',
         ['infected', 'noninfected'], 9927, 'output/10k_v2.0/wgcna'),
        ('10k_v2.0', 'sex',
         'output/10k_v2.0/wgcna/sex/vq_wgcna_comparison/vq_wgcna_overlap_sex_sequential.csv',
         ['female', 'male'], 9927, 'output/10k_v2.0/wgcna'),
        ('25k_v2.0', 'sex',
         'output/25k_v2.0/wgcna/sex/vq_wgcna_comparison/vq_wgcna_overlap_sex_sequential.csv',
         ['female', 'male'], 22597, 'output/25k_v2.0/wgcna'),
    ]
    for run, comp, ov_path, groups, universe, wgcna_dir in overlap_configs:
        ov = load_rows(ov_path)
        mmap = module_go_map(wgcna_dir, comp, groups)
        OUT.append(overlap_table(
            ov, mmap, universe,
            f"tab:vq-wgcna-{run_label[run]}-{comp}",
            rf"FDR-significant VQ code $\times$ WGCNA module overlaps, "
            rf"{run_label[run]} gene set, {comp} comparison. Fold = observed / "
            rf"expected overlap under random gene membership."))
        OUT.append("")

    with open(args.out, 'w') as f:
        f.write("\n".join(OUT) + "\n")
    n_rows = sum(1 for l in OUT if l.strip().endswith("\\\\") or "\\hline" in l)
    print(f"Wrote {args.out} ({n_rows} table rows)")

    # Split into the two files \input by manuscript.tex: GO tables first,
    # then the VQ-WGCNA overlap tables.
    lines = OUT
    split = next((i for i, l in enumerate(lines)
                  if "\\begin{longtable}{r l c c c c c p{4.6cm}}" in l),
                 len(lines))
    hdr = "% Auto-generated by scripts/generate_ms_tables.py — do not edit by hand.\n"
    with open('manuscript_tables_vqgo.tex', 'w') as f:
        f.write(hdr + "\n".join(lines[:split]) + "\n")
    with open('manuscript_tables_overlap.tex', 'w') as f:
        f.write(hdr + "\n".join(lines[split:]) + "\n")
    print("Wrote manuscript_tables_vqgo.tex and manuscript_tables_overlap.tex")

    # Quick stats
    print("\nOverlap FDR-significant counts:")
    for run, comp, ov_path, groups, universe, wgcna_dir in overlap_configs:
        ov = load_rows(ov_path)
        n = sum(1 for r in ov if float(r['fisher_q']) < 0.05)
        print(f"  {run} {comp}: {n}")


if __name__ == '__main__':
    main()
